### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by RobertoSnap** [aleixmorgadas/nem-library-docs#10]
**Expected Behaviour**

When importing NEM-library you will get several WARNING's "Critical dependency: the request of a dependency is an expression". 

Maybe connected to [https://github.com/webpack/webpack/issues/196](https://github.com/webpack/webpack/issues/196)

**Current Behaviour**

When running ```ng serve``` I get these warnings. 

Its not only har-validator, dependent on sub library to run it will give warning s about other also.

```
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-01-22T15:28:22.114Z
Hash: b3b703d400c94e2c31cd
Time: 13250ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 26.1 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 548 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 33.5 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 20.7 MB [initial] [rendered]

WARNING in ./node_modules/har-validator/node_modules/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (C:\www\test1\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\www\test1\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\www\test1\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\www\test1\node_modules\webpack\lib\Compiler.js:502:17)
    at C:\www\test1\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\www\test1\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\www\test1\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./node_modules/har-validator/node_modules/ajv/lib/async.js
 @ ./node_modules/har-validator/node_modules/ajv/lib/ajv.js
 @ ./node_modules/har-validator/lib/node4/promise.js
 @ ./node_modules/request/lib/har.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise-native/lib/rp.js
 @ ./node_modules/nem-library/dist/src/infrastructure/MosaicHttp.js
 @ ./node_modules/nem-library/dist/src/infrastrcture.js
 @ ./node_modules/nem-library/dist/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/har-validator/node_modules/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (C:\www\test1\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\www\test1\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\www\test1\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\www\test1\node_modules\webpack\lib\Compiler.js:502:17)
    at C:\www\test1\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\www\test1\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\www\test1\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./node_modules/har-validator/node_modules/ajv/lib/compile/index.js
 @ ./node_modules/har-validator/node_modules/ajv/lib/ajv.js
 @ ./node_modules/har-validator/lib/node4/promise.js
 @ ./node_modules/request/lib/har.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise-native/lib/rp.js
 @ ./node_modules/nem-library/dist/src/infrastructure/MosaicHttp.js
 @ ./node_modules/nem-library/dist/src/infrastrcture.js
 @ ./node_modules/nem-library/dist/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/har-validator/node_modules/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (C:\www\test1\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\www\test1\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\www\test1\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\www\test1\node_modules\webpack\lib\Compiler.js:502:17)
    at C:\www\test1\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\www\test1\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\www\test1\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./node_modules/har-validator/node_modules/ajv/lib/async.js
 @ ./node_modules/har-validator/node_modules/ajv/lib/ajv.js
 @ ./node_modules/har-validator/lib/node4/promise.js
 @ ./node_modules/request/lib/har.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise-native/lib/rp.js
 @ ./node_modules/nem-library/dist/src/infrastructure/MosaicHttp.js
 @ ./node_modules/nem-library/dist/src/infrastrcture.js
 @ ./node_modules/nem-library/dist/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Compiled with warnings.
```

**Steps to reproduce**

1.  Create a new angular 5 project - ```ng new test1```
2. ```npm install nem-library``` 
3. Add this code to **app.component.ts** 
```js 

import { Component } from '@angular/core';
import {BrainWallet, BrainPassword, NetworkTypes, NEMLibrary} from "nem-library";

// Initialize NEMLibrary for TEST_NET Network
NEMLibrary.bootstrap(NetworkTypes.TEST_NET);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  createSeed(): string {
    return "GDASGDSAG";
  }

  createWallet() {
    const brainPassword = new BrainPassword(this.createSeed());
    const brainWallet = BrainWallet.create("Test wallet 1", brainPassword);
    return brainWallet;
  }
}

```
4. Add this button to app.component.html
```<button (click)="createWallet()">Test Wallet</button>```
5. Run ```ng serve```

**Comment by thomas-tran** [comment]
How did you resolve this issue?

**Comment by aleixmorgadas** [comment]
Update to the latest version and it should be solved

**Comment by thomas-tran** [comment]
Hi Aleix,

Are you still working on the typescript project for Nem and Nem2 SDK?

Thomas

**Comment by thomas-tran** [comment]
Ok I thought Nem abandon all the project include catapult cause there were
no activities for the last few months.

Just curious about the nem2 library why you did not implement the secure
message like nis1?

**Comment by aleixmorgadas** [comment]
Well, it's not abandoned at all, the nem2-sdk works well for the current PoS that developers are doing. It's true that there are some missing features, but it's not under release candidate version yet.

About secure message, a matter of prioritization. I think @nemtech will be happy to help you if you want to help in developing that feature for nem2-sdk :smile:

**Comment by thomas-tran** [comment]
HI Aleix,

For the secure message, will it be the same as NIS1, If yes, I can help to
port the code over? If not, please let me know the algorithm.

Thanks
Thomas

**Comment by aleixmorgadas** [comment]
I would suggest you open an issue at [github.com/nemtech/nem2-sdk-typescript-javascript/issues](https://github.com/nemtech/nem2-sdk-typescript-javascript/issues).
